[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "easyocr>=1.7.2",
    "fastapi>=0.138.0",
    "opencv-python>=5.0.0.93",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "pdf2image>=1.17.0",
    "pdfplumber>=0.11.10",
    "pillow>=12.2.0",
    "pymupdf>=1.27.2.3",
    "python-multipart>=0.0.32",
    "uvicorn>=0.49.0",
    "rapidocr-onnxruntime==1.4.4",
]